(in-package #:sorcery-sdl2)

(defparameter *translate*
  '(:french ((energy . "Energie")
             (score . "Score")
             (inventory . "Inventaire")
             (pause . "PAUSE")
             (youare . "Vous êtes ")
             (wastelands . "dans les terres désolées")
             (waterfall . "à la cascade")
             (tunnel . "dans le tunnel")
             (tunnelmouth . "à l'entrée du tunnel")
             (stonehenge . "à Stonehenge")
             (nearstonhenge . "près de Stonehenge")
             (nearvillage . "près du village")
             (palace . "dans le palace")
             (nearpalace . "près du palace")
             (castle . "dans le chateau")
             (outsidecastle . "hors du chateau")
             (nearcastle . "près du chateau")
             (abovecastle . "en haut du chateau")
             (sanctuary . "dans le sanctuaire")
             (dungeon . "dans le donjon")
             (woods . "dans les bois")
             (strongroom . "dans la chambre forte")
             (gameover . "GAME OVER")
             (victory . "VICTOIRE")
             (start . "Appuyez sur 's' pour jouer")
             (released . "Apprentis sorciers libérés")
             (released-end . "/8")
             (keyboard . "Clavier :")
             (kb-up . "HAUT : ")
             (kb-left . "GAUCHE : ")
             (kb-right . "DROITE : ")
             (kb-fire . "FEU : ")
             (kb-pause . "Pause : ")
             (kb-lang . "Langue (Anglais/Français) : ")
             (dave . "dave")
             (andy . "andy")
             (ian . "ian")
             (steve . "steve")
             (tricia . "tricia"))
    :english ((energy . "Energy")
              (score . "Score")
              (inventory . "Inventory")
              (pause . "PAUSE")
              (youare . "You are ")
              (wastelands . "into the wastelands")
              (waterfall . "at the waterfall")
              (tunnel . "in the tunnel")
              (tunnelmouth . "à l'entrée du tunnel")
              (stonehenge . "at Stonehenge")
              (nearstonhenge . "near Stonehenge")
              (nearvillage . "near the village")
              (palace . "in the palace")
              (nearpalace . "near the palace")
              (castle . "in the castle")
              (outsidecastle . "outside the castle")
              (nearcastle . "near the castle")
              (abovecastle . "above the castle")
              (sanctuary . "in the sanctuary")
              (dungeon . "in the dungeon")
              (woods . "in the woods")
              (strongroom . "in the strong room")
              (gameover . "GAME OVER")
              (victory . "VICTORY")
              (released . "Apprentice sorcerers released")
              (released-end . "/8")
              (start . "Press 's' to start")
              (keyboard . "Keyboard :")
              (kb-up . "UP : ")
              (kb-left . "LEFT : ")
              (kb-right . "RIGHT : ")
              (kb-fire . "FIRE : ")
              (kb-pause . "Pause : ")
              (kb-lang . "Language (english/french) : ")
              (dave . "dave")
              (andy . "andy")
              (ian . "ian")
              (steve . "steve")
              (tricia . "tricia"))))

(defun string-from-key (language key)
    (cdr (assoc key (getf *translate* language))))
